service: fastapi-microservice-template

frameworkVersion: "3"

provider:
    name: aws
    region: ${opt:region, 'us-west-1'}
    stage: ${opt:stage, 'dev'}
    ecr:
        images:
            appimage:
                path: ./
                file: Dockerfile.lambda
                platform: linux/amd64

    httpApi:
        cors: true
    environment:
        STAGE: ${self:provider.stage}
    
functions:
    app:
        image:
            name: appimage
        events:
            - httpApi:
                  path: "*"
